name: py
    
on:
  schedule:
    - cron: '30 18,6 * * *'
    
jobs:
  build:
        runs-on: ubuntu-latest
    
        steps:
          - name: checkout repo content
            uses: actions/checkout@v2 # checkout the repository content to github runner.
          - name: setup python
            uses: actions/setup-python@v2
            with:
              python-version: 3.8 #install the python needed
          - name: execute py script # run the run.py to get the latest data
            run: |
              python -m pip install simple-http-server
              python -m http.server
              python run.py
              
            env:
              key: ${{ secrets.key }} # if run.py requires passwords..etc, set it as secrets
          - name: export index
